# Generated by Django 3.2.4 on 2021-07-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0003_auto_20210708_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bolg',
            new_name='blog',
        ),
    ]
